SWDEV-411709 - default hip version to 5.7 and filename/path for .hipVersion
ROCm-Developer-Tools/HIPCC pull request #111
Opened 2023-07-18 16:56 UTC by agunashe

SWDEV-411709 - default hip version to 5.7 and filename/path for .hipVersion

2023-07-19 17:13 UTC, gargrahul approved these changes
LGTM for now

This will need further corrections to avoid updating HIP base versions.

2023-07-21 15:42 UTC, kzhuravl requested changes

2023-07-21 15:42 UTC, kzhuravl commented on bin/hipvars.pm
> +    parse_config_file("$hipvars::HIP_PATH/share/hip/version", \%hipVersion);
What if HIP_PATH has spaces in it? It won't work.

2023-07-21 16:23 UTC, kzhuravl approved these changes
It is not executing any commands, so having whitespaces without double quotes is fine.

2023-07-21 16:29 UTC, merged