Cleanup existing double quote handling
ROCm-Developer-Tools/HIPCC pull request #112
Opened 2023-07-20 19:49 UTC by kzhuravl

2023-07-20 20:17 UTC, kzhuravl commented
This essentially only introduces double quotes to windows, but not for linux

2023-07-20 21:40 UTC, yxsamliu commented
Is this because Linux has the slightest chance to see paths with space, so we do not want to pollute the command line with quotes?

2023-07-20 22:00 UTC, kzhuravl commented
> Is this because Linux has the slightest chance to see paths with space, so we do not want to pollute the command line with quotes?

I ran into some issues with the original implementation when building rocTHRUST on linux, and this patch seemed to fix it. Unfortunately, I am not familiar with whitespaces on linux. Evgeny mentioned this approach in one of the cherry-pick reviews, so I went ahead and did it.

@emankov, any thoughts on whitespaces on linux? based on my googling, whitespaces in paths happen on linux and are also handled with double or single quotes around the path... https://stackoverflow.com/questions/12902227/how-to-input-a-path-with-a-white-space

2023-07-21 11:13 UTC, emankov requested changes

2023-07-21 11:13 UTC, emankov commented on bin/hipcc.pl
> +    if ($isWindows) {
I think we can normalize paths always and unconditionally. Clang driver, for instance, does it the same way.

2023-07-21 11:13 UTC, emankov commented on bin/hipvars.pm
>      } elsif (can_run("$CUDA_PATH/bin/nvcc") or can_run("nvcc")) {
We need CUDA_PATH double-quoted too.

2023-07-21 11:13 UTC, emankov commented on bin/hipvars.pm
> +  $doubleQuote = "\"";
Let's try to leave it as an unconditional const `"\""`.

2023-07-21 13:52 UTC, yxsamliu commented
The failure on rocThrust could be due to some corner case that is not handled when quoting the options.

I am OK with this patch since we want to deprecate hipcc and ask people to use clang directly. I feel not worth the effort to spend too much time on hipcc.

2023-07-21 15:12 UTC, emankov commented
> I am OK with this patch since we want to deprecate hipcc and ask people to use clang directly. I feel not worth the effort to spend too much time on hipcc.

Unfortunately, we need to fix the nvcc path in hipcc after all, cause hipcc is still going to be shipped in at least two HIP SDK releases for Windows.

2023-07-21 19:06 UTC, emankov approved these changes
LGTM, thanks!

2023-07-22 02:27 UTC, kzhuravl commented
fyi, I am getting rocThrust build failures in internal ci when returning a double quote for linux path:

2023-07-22T00:57:36.221388549Z clang: error: invalid target ID 'gfx90a\:xnack+'; format is a processor name followed by an optional colon-delimited list of features followed by an enable/disable sign (e.g., 'gfx908:sramecc+:xnack-')

2023-07-22 02:28 UTC, kzhuravl commented
Is everyone ok with not putting a double quotes around paths on linux for now? @emankov?

2023-07-23 03:58 UTC, yxsamliu commented
> fyi, I am getting rocThrust build failures in internal ci when returning a double quote for linux path:
> 
> 2023-07-22T00:57:36.221388549Z clang: error: invalid target ID 'gfx90a:xnack+'; format is a processor name followed by an optional colon-delimited list of features followed by an enable/disable sign (e.g., 'gfx908:sramecc+:xnack-')

That's a valid target ID. I suspect it was quoted twice, e.g. "--offload-arch='gfx90a:xnack+'", then clang gets an option value containing a single quote.

2023-07-23 19:10 UTC, emankov commented
> fyi, I am getting rocThrust build failures in internal ci when returning a double quote for linux path:
> 
> 2023-07-22T00:57:36.221388549Z clang: error: invalid target ID 'gfx90a:xnack+'; format is a processor name followed by an optional colon-delimited list of features followed by an enable/disable sign (e.g., 'gfx908:sramecc+:xnack-')

I do not see any double quotes in the message. Could you please provide us with the clang command line, if possible?

2023-07-23 19:35 UTC, emankov requested changes
The change should revise only path-containing options and leave untouched the rest of the options.

2023-07-23 19:35 UTC, emankov commented on bin/hipcc.pl
> -    $toolArgs .= " \"$arg\"" unless $swallowArg;
Here in the first commit, the non-path, actually all the args for passing to a tool, were touched. On Linux, double quotes were removed, and on Windows, they were left. I missed it.

2023-07-26 17:10 UTC, david-salinas approved these changes
LGTM ... but, I'd like to see if we can get a Windows build to verify no regressions.

2023-07-26 18:28 UTC, kzhuravl commented on bin/hipcc.pl
> -    $toolArgs .= " \"$arg\"" unless $swallowArg;
I had to undo this due to issues while building rocThrust.

2023-07-26 18:47 UTC, emankov approved these changes
LGTM, thanks!

2023-07-27 12:23 UTC, merged