hipcc ignores --rocm-path if ROCM_PATH set
ROCm-Developer-Tools/HIPCC pull request #27
Opened 2022-08-03 20:15 UTC by david-salinas

swdev-343493 - hipcc ignores --rocm-path
    swdev-342125 - Fix ROCM_PATH issues

2022-08-08 18:03 UTC, scchan commented
Could you please split it into 2 patches - one with the clean-up/refactoring and the other with the actual fix?  That would make the fix easier to follow

2022-08-08 21:29 UTC, scchan requested changes
As mentioned in my previous comment, could you put the code renaming/refactoring changes in a separate PR because it's difficult to isolate and to reason the logic fixing the --rocm-path issue.

2022-08-08 21:29 UTC, scchan commented on src/hipBin_base.h
> +	// we need to use --rocm-path option
This function name should be corrected too?

2022-08-08 21:29 UTC, scchan commented on src/hipBin_amd.h
> +  const string& roccmPath = getRocmPath();
fix `roccmPath` name

2022-08-09 19:58 UTC, david-salinas commented
Abandoning this PR in favour of https://github.com/ROCm-Developer-Tools/HIPCC/pull/28

2022-08-09 19:58 UTC, closed without merging