Refactor roccm to rocm and env var names
ROCm-Developer-Tools/HIPCC pull request #30
Opened 2022-08-10 18:51 UTC by david-salinas

2022-08-10 21:26 UTC, scchan requested changes

2022-08-10 21:26 UTC, scchan commented on src/hipBin_amd.h
> +  const string& roccmPath = getRocmPath();
change `roccmPath`

2022-08-10 21:26 UTC, scchan commented on src/hipBin_base.h
> +  vector<string> rocmPathStrs = { "-R", "--rocm-path", "-rocm-path", "--R" };
This is a breaking change to the command line interface.  It's also creates an incompatiblity with the perl version.  If we need to change it then we should follow a deprecation process.

2022-08-10 21:26 UTC, scchan commented on src/hipBin_base.h
> +  cout << "  --rocm-path,  -R    :"
breaking change, see my comment below

2022-08-11 14:28 UTC, david-salinas commented on src/hipBin_amd.h
> +  const string& roccmPath = getRocmPath();
good catch.  Actually there are a couple of other instances of the use of "roccm".  I'll clean those up too.

2022-08-11 14:48 UTC, david-salinas commented on src/hipBin_base.h
> +  vector<string> rocmPathStrs = { "-R", "--rocm-path", "-rocm-path", "--R" };
The Clang command line documentation documents the option string as "--rocm-path", with the dash between "rocm" and "path":  https://github.com/llvm/llvm-project/blob/main/clang/docs/ClangCommandLineReference.rst  
Also all of the clang tests use "--rocm-path".

I have a PR to change/added code to the Perl script [ https://github.com/ROCm-Developer-Tools/HIP/pull/2853 : btw can you review that one too?  :-) ] to check for "--rocm-path", so there shouldn't be an incompatibility.

2022-08-11 14:49 UTC, david-salinas commented on src/hipBin_base.h
> +  cout << "  --rocm-path,  -R    :"
This is the correct form of the string according to the Clang documentation, and clang tests.  See my response to the other comment.

2022-08-11 17:02 UTC, david-salinas commented on src/hipBin_base.h
> +  vector<string> rocmPathStrs = { "-R", "--rocm-path", "-rocm-path", "--R" };
Ok, so I just checked hipconfig.pl ... it does use "rocmpath".  But, the change here won't technically break compatibility, since hipconfig does not depend directly on "hipcc" (bin or pl).  But the hipconfig option is its own option, it's not supposed to necessarily match the compiler/clang option.  But I think hipcc.bin's handling of "-rocpath" should match the clang option.

2023-08-02 21:13 UTC, kzhuravl commented
Do we still need this PR? If yes, can you rebase it?

2023-08-16 19:24 UTC, kzhuravl commented
Closing since no reply. Let me know if this is still needed.

2023-08-16 19:24 UTC, closed without merging