Respect --rocm-path option over ROCM_PATH environment variable
ROCm-Developer-Tools/HIPCC pull request #31
Opened 2022-08-10 19:13 UTC by david-salinas

2022-08-10 22:35 UTC, scchan requested changes

2022-08-10 22:35 UTC, scchan commented on src/hipBin_amd.h
> +  setrocm_pathOption(argv);
This adds an extra pass over argv, which is inefficient.  If possible we shoud use the general arg parsing loop to parse the rocm-path option.

2022-08-10 22:35 UTC, scchan commented on src/hipBin_base.h
> +    string arg = argv.at(argcount);
should use `cosnt string&`, it's not being modified so should avoid making a copy

2022-08-10 22:35 UTC, scchan commented on src/hipBin_base.h
> +      string arg_name = arg.substr(0,foundEquals);
you don't need to create a new copy just to do a string compare below

2022-08-11 16:27 UTC, david-salinas commented on src/hipBin_amd.h
> +  // delay constructing paths until we parse compiler options that may override these.
Yeah I should remove this comment.  It's left over from when I had commented out the call to constructCompilerPath().

And I think you're right we should move these to "executeHIPCCCmd()".  Though interestingly, I think I've found a bug in hipcc.bin where it doesn't get HIP_LIB_PATH right if it's not already set in the environment.

2022-08-11 16:30 UTC, david-salinas commented on src/hipBin_base.h
> +    string arg = argv.at(argcount);
yup.  Will fix .

2022-08-11 19:15 UTC, david-salinas commented on src/hipBin_amd.h
> +  setrocm_pathOption(argv);
I agree.  I was looking at improving that loop and just putting it into a proper function, but I was a little concerned about "feature creep" on this work.  But I should at least (hack) add in a check in the loop below this, for now?  But I would like to see some proper "options processing" in this code too.

2022-08-11 19:17 UTC, david-salinas commented on src/hipBin_base.h
> +      string arg_name = arg.substr(0,foundEquals);
agreed

2022-08-12 19:33 UTC, scchan requested changes

2022-08-12 19:33 UTC, scchan commented on src/hipBin_amd.h
> +      string rocmPathOpt = rocmPathOpts.at(i);
It would be much cleaner to have a range-base loop to iterate over the vector.  Also, get a const ref to the string instead of making a new copy

2022-08-12 19:33 UTC, scchan commented on src/hipBin_amd.h
> +      if (hipBinUtilPtr_->stringRegexMatch(arg, pattern))  {
regex tends to be expensive and it seems like overkill to me

2022-08-15 17:17 UTC, david-salinas commented on src/hipBin_amd.h
> +      string rocmPathOpt = rocmPathOpts.at(i);
True.  Will change.

2022-08-15 17:18 UTC, david-salinas commented on src/hipBin_amd.h
> +      // match arg with the starting of targetOpt
typo . I used the targetOpt code below as a template.  Will fix.

2022-08-15 17:38 UTC, david-salinas commented on src/hipBin_amd.h
> +      if (hipBinUtilPtr_->stringRegexMatch(arg, pattern))  {
ok, fair enough.  So just a str::compare(), or == ?

I should point out that we use this stringRegexMatch a fair bit in this arg processing loop.  Maybe something we can address in another PR?

2022-11-03 22:59 UTC, scchan requested changes

2022-11-03 22:59 UTC, scchan commented on src/hipBin_base.h
> +  string hipVersion_;
Any reason you are moving this block of code?  Also, I'm not sure if you intent to change the functions above from private to protected.

2022-11-03 22:59 UTC, scchan commented on src/hipBin_amd.h
> +  const string& roccmPath = getRoccmPath();
I know the typo "roccm" was already there before but do you mind fixing it?

2022-11-04 18:21 UTC, david-salinas commented on src/hipBin_amd.h
> +  const string& roccmPath = getRoccmPath();
I split out the renaming/refactoring/clean-up into a separate PR:  https://github.com/ROCm-Developer-Tools/HIPCC/pull/30

2022-11-04 18:28 UTC, david-salinas commented on src/hipBin_base.h
> +  string hipVersion_;
I had to make the above member functions protected because they used to be called from the constructor for HipBinBase and now we're calling them from "HipBinAmd::executeHipCCCmd", after we've processed the argv (specifically we need that for processing --rocm-path)

2022-11-18 00:12 UTC, scchan approved these changes
LGTM

2022-11-19 17:31 UTC, merged