Several HIPCC improvements
ROCm-Developer-Tools/HIPCC pull request #59
Opened 2023-02-20 18:19 UTC by kzhuravl

- Separate hipcc package
- Move hipcc.pl and hipconfig.pl into HIPCC project
- Minor cleanups

2023-03-05 23:30 UTC, kzhuravl commented
ping

2023-03-07 15:21 UTC, scchan commented
There has been a couple of changes to hipcc.pl recently.  I'd suggest that we wait for https://github.com/ROCm-Developer-Tools/HIP/pull/3174 to be merged into HIP, then freeze all the hipcc related files until this PR lands.

2023-03-07 15:28 UTC, scchan requested changes

2023-03-07 15:28 UTC, scchan commented on CMakeLists.txt
> +set(CPACK_DEBIAN_PACKAGE_DEPENDS "libfile-basedir-perl, libfile-copy-recursive-perl, libfile-listing-perl, libfile-which-perl, liburi-encode-perl, perl (>= 5.0)")
We should probably add the hip-dev and rocm-llvm packages here.

2023-03-07 15:28 UTC, scchan commented on CMakeLists.txt
> +set(CPACK_RPM_PACKAGE_REQUIRES "perl >= 5.0, perl-File-BaseDir, perl-File-Listing, perl-File-Which, perl-URI-Encode")
We should probably add the hip-dev and rocm-llvm packages here.

2023-03-07 15:45 UTC, kzhuravl commented on CMakeLists.txt
> +set(CPACK_RPM_PACKAGE_REQUIRES "perl >= 5.0, perl-File-BaseDir, perl-File-Listing, perl-File-Which, perl-URI-Encode")
agreed on rocm-llvm. can you elaborate on why we need hip-dev?

2023-03-07 15:47 UTC, kzhuravl commented on CMakeLists.txt
> +  set(HIP_VERSION_PATCH 4 PARENT_SCOPE)
Any suggestions on how to deal with https://github.com/ROCm-Developer-Tools/HIPCC/blob/develop/src/hipBin_base.h#L363 then?

2023-03-08 15:33 UTC, scchan commented on CMakeLists.txt
> +set(CPACK_RPM_PACKAGE_REQUIRES "perl >= 5.0, perl-File-BaseDir, perl-File-Listing, perl-File-Which, perl-URI-Encode")
hip-dev installs the HIP headers and runtime

2023-03-08 15:41 UTC, kzhuravl commented on CMakeLists.txt
> +set(CPACK_RPM_PACKAGE_REQUIRES "perl >= 5.0, perl-File-BaseDir, perl-File-Listing, perl-File-Which, perl-URI-Encode")
ok, but what if I want to compile hip sources on a bare ubuntu, then I won't be able to do it? P.S. I can compile llvm on bare ubuntu and then compile opencl kernels without opencl being installed...

2023-03-08 15:42 UTC, scchan commented on CMakeLists.txt
> +  set(HIP_VERSION_PATCH 4 PARENT_SCOPE)
Those are C-strings being passed to readConfigMap to get the version number parsed from the .hipVersion file.
The HIP_VERSION_* cmake variables aren't being used to define anything in the program.

2023-03-08 15:47 UTC, scchan commented on CMakeLists.txt
> +set(CPACK_RPM_PACKAGE_REQUIRES "perl >= 5.0, perl-File-BaseDir, perl-File-Listing, perl-File-Which, perl-URI-Encode")
You can compile HIP program sources if you have llvm and hip-dev installed. hipcc is not a requirement.
The use case is for someone doing "apt-get install hipcc" then that should also pull in llvm, hip-dev because we want it to just work?

2023-03-08 15:53 UTC, scchan commented on CMakeLists.txt
> +set(CPACK_RPM_PACKAGE_REQUIRES "perl >= 5.0, perl-File-BaseDir, perl-File-Listing, perl-File-Which, perl-URI-Encode")
I guess what you are using is like someone could write a C++ program source that doesn't depend on the C++ headers but that's not a very practical right?  That's the reason why g++ depends on libstdc++-dev.

2023-03-21 14:26 UTC, kzhuravl commented on CMakeLists.txt
> +  set(HIP_VERSION_PATCH 4 PARENT_SCOPE)
Fixed in the next PR update.

2023-03-21 14:29 UTC, kzhuravl commented on CMakeLists.txt
> +set(CPACK_DEBIAN_PACKAGE_DEPENDS "libfile-basedir-perl, libfile-copy-recursive-perl, libfile-listing-perl, libfile-which-perl, liburi-encode-perl, perl (>= 5.0)")
Fixed in the next PR update.

2023-03-21 14:29 UTC, kzhuravl commented on CMakeLists.txt
> +set(CPACK_RPM_PACKAGE_REQUIRES "perl >= 5.0, perl-File-BaseDir, perl-File-Listing, perl-File-Which, perl-URI-Encode")
Fixed in the next PR update.

2023-03-22 19:21 UTC, david-salinas approved these changes

2023-04-03 18:49 UTC, frepaul requested changes

2023-04-03 18:49 UTC, frepaul commented on CMakeLists.txt
Need to added dependency to rocm-core, with same logic as hip. This is needed to help track rocm version and easy clean-up of all rocm files during uninstall.

2023-04-03 18:49 UTC, frepaul commented on CMakeLists.txt
> +set(CPACK_RPM_PACKAGE_REQUIRES "hip-dev, perl >= 5.0, perl-File-BaseDir, perl-File-Listing, perl-File-Which, perl-URI-Encode, rocm-llvm")
should be hip-devel instead of hip-dev.

2023-04-03 19:15 UTC, kzhuravl commented on CMakeLists.txt
> +set(CPACK_RPM_PACKAGE_REQUIRES "hip-dev, perl >= 5.0, perl-File-BaseDir, perl-File-Listing, perl-File-Which, perl-URI-Encode, rocm-llvm")
fixed

2023-04-03 19:29 UTC, kzhuravl commented on CMakeLists.txt
Done.

2023-04-03 19:41 UTC, raramakr commented
LGTM

2023-04-03 20:50 UTC, frepaul approved these changes
Code to remove dependency on rocm-core if build from github or by local user is not present. It can be added as sperate PR though.

2023-04-03 21:47 UTC, merged