Documentation - Add sphinx configs for Read the Docs/RTD
ROCm-Developer-Tools/HIPCC pull request #64
Opened 2023-04-12 17:50 UTC by samjwu

Doc files (docs/*.md) are taken from README.md

Currently set as draft; will mark ready for review when RTD integration and site preview is done 

Uses rocm-docs-core template for documentation
Rationale:
 - https://github.com/RadeonOpenCompute/rocm-docs-core#purpose

2023-04-13 15:58 UTC, david-salinas requested changes

2023-04-13 15:58 UTC, david-salinas commented on docs/index.md
> +`hipcc` is a compiler driver utility that will call clang or nvcc, depending on target, and pass the appropriate include and library options for the target compiler and HIP infrastructure. Historical
We're in the process of migrating the Perl versions of hipcc/hipconfig from HIP repository into this (HIPCC) repository.  So we really only need the first sentence in this line; everything in this line, after "... target compiler and HIP infrastructure." can be removed.

2023-04-13 15:58 UTC, david-salinas commented on docs/index.md
> +
Since we're migrating the Perl versions of hipcc/hipconfig here, I think we should add some information about how to use/enable the C++ binary version versus the default Perl versions.  Can we add this:

There is both a Perl version, and a C++ executable version of the hipcc/hipconfig compiler driver utilities provided.  Currently, by default the Perl version is used when 'hipcc' is called.  To enable the C++ executable versions, set the environment variable  "HIP_USE_PERL_SCRIPTS=0".

2023-04-13 23:25 UTC, samjwu commented on docs/index.md
> +`hipcc` is a compiler driver utility that will call clang or nvcc, depending on target, and pass the appropriate include and library options for the target compiler and HIP infrastructure. Historical
Done in [fe1b27d](https://github.com/ROCm-Developer-Tools/HIPCC/pull/64/commits/fe1b27d80d5df9afe00ce360da5b5bb4b97a1229)

2023-04-13 23:25 UTC, samjwu commented on docs/index.md
> +
Added in [fe1b27d](https://github.com/ROCm-Developer-Tools/HIPCC/pull/64/commits/fe1b27d80d5df9afe00ce360da5b5bb4b97a1229)

2023-04-13 23:25 UTC, samjwu commented on docs/env.md
> +- HSA_PATH        : Path to HSA dir (defaults to ../../hsa relative to abs_path of hipcc). Used on AMD platforms only.
Removed in [fe1b27d](https://github.com/ROCm-Developer-Tools/HIPCC/pull/64/commits/fe1b27d80d5df9afe00ce360da5b5bb4b97a1229)

2023-04-14 15:30 UTC, david-salinas commented
Thanks Sam.  Ok, I think this looks good now.  I'm going to ask Rahul to take a quick look.  But I think we can/should be able to go ahead with this PR and take it out of Draft mode, and try to land/merge it soon.

2023-04-21 20:33 UTC, david-salinas approved these changes
LGTM

2023-04-24 16:48 UTC, merged